set laststatus=2 " enable status line
set number

set shiftwidth=4
set tabstop=4
set softtabstop=4
set smarttab
set expandtab

filetype plugin indent on
syntax on

set nohlsearch
set incsearch

set title

colorscheme gruvbox
set background=dark
set termguicolors

set noswapfile

set hidden " allow hidden buffers to remain open

packadd! comment
packadd! editorconfig
