set laststatus=2 " enable status line

set shiftwidth=4
set tabstop=4
set softtabstop=4
set smarttab
set expandtab

filetype indent on

set nohlsearch
set incsearch

colorscheme gruvbox
set background=dark
set termguicolors

packadd! comment
packadd! editorconfig

